use crate::core::policy::PolicyEngine;
use crate::models::{CleanupDisposition, CleanupFinding, SystemProfile};
use anyhow::{bail, Context, Result};
use dirs::{cache_dir, download_dir, home_dir};
use std::{fs, path::PathBuf};

#[derive(Debug, Clone)]
pub struct CleanupEngine {
    policy: PolicyEngine,
}

impl CleanupEngine {
    pub fn new(policy: PolicyEngine) -> Self {
        Self { policy }
    }

    pub fn scan(&self, profile: &SystemProfile) -> Result<Vec<CleanupFinding>> {
        let mut findings = Vec::new();

        if let Some(cache) = cache_dir() {
            findings.push(self.inspect_dir("user-cache", "User cache", cache.clone(), CleanupDisposition::SafeAuto, true, "Rebuildable cache files"));
            findings.push(self.inspect_dir(
                "thumbnails",
                "Thumbnail cache",
                cache.join("thumbnails"),
                CleanupDisposition::SafeAuto,
                true,
                "Regenerated by desktop shell when needed",
            ));
            findings.push(self.inspect_dir(
                "browser-cache",
                "Browser cache",
                cache.join("mozilla"),
                CleanupDisposition::Review,
                true,
                "Safe in principle, but user may want warm cache kept",
            ));
        }

        if let Some(home) = home_dir() {
            findings.push(self.inspect_dir(
                "trash",
                "Trash contents",
                home.join(".local/share/Trash/files"),
                CleanupDisposition::Review,
                true,
                "User-owned deleted files need explicit confirmation",
            ));
            findings.push(self.inspect_dir(
                "crash-dumps",
                "Crash dumps",
                home.join(".local/share/systemd/coredump"),
                CleanupDisposition::Review,
                true,
                "Useful for debugging. Keep by default unless approved",
            ));
        }

        if let Some(downloads) = download_dir() {
            findings.push(self.inspect_large_downloads(downloads));
        }

        for candidate in [
            PathBuf::from("/var/tmp"),
            PathBuf::from("/tmp"),
            PathBuf::from("/var/cache"),
            PathBuf::from("/var/crash"),
        ] {
            let disposition = if candidate == PathBuf::from("/var/cache") {
                CleanupDisposition::Review
            } else {
                CleanupDisposition::SafeAuto
            };
            findings.push(self.inspect_dir(
                &candidate.to_string_lossy(),
                &format!("{} scan", candidate.display()),
                candidate.clone(),
                disposition,
                true,
                "System temporary or cache directory",
            ));
        }

        if profile.package_managers.iter().any(|p| p == "flatpak") {
            findings.push(CleanupFinding {
                id: "flatpak-unused-runtimes".to_string(),
                label: "Flatpak unused runtimes".to_string(),
                path: "flatpak uninstall --unused --assumeno".to_string(),
                bytes: 0,
                disposition: CleanupDisposition::Review,
                rationale: "Requires runtime dependency preview before execution".to_string(),
                destructive: true,
                rollback_kind: Some("reinstall-manifest".to_string()),
            });
            findings.push(self.inspect_dir(
                "flatpak-cache",
                "Flatpak cache",
                home_dir().unwrap_or_default().join(".local/share/flatpak/.cache"),
                CleanupDisposition::SafeAuto,
                true,
                "Flatpak temporary transaction and metadata cache",
            ));
        }

        if profile.package_managers.iter().any(|p| p == "snap") {
            findings.push(self.inspect_dir(
                "snap-cache",
                "Snap cache",
                PathBuf::from("/var/lib/snapd/cache"),
                CleanupDisposition::SafeAuto,
                true,
                "Snapd download and metadata cache",
            ));
        }

        // Distro-specific package manager caches
        for (pm, path, label) in [
            ("apt", "/var/cache/apt/archives", "Apt package cache"),
            ("dnf", "/var/cache/dnf", "Dnf metadata and package cache"),
            ("pacman", "/var/cache/pacman/pkg", "Pacman package cache"),
            ("zypper", "/var/cache/zypper", "Zypper metadata and package cache"),
        ] {
            if profile.package_managers.iter().any(|p| p == pm) {
                findings.push(self.inspect_dir(
                    &format!("{pm}-cache"),
                    label,
                    PathBuf::from(path),
                    CleanupDisposition::Review,
                    true,
                    "Previous versions of installed or removed packages",
                ));
            }
        }

        Ok(findings
            .into_iter()
            .filter(|f| f.bytes > 0 || f.path.contains("flatpak") || f.path.contains("/var/cache"))
            // A finding that cannot legally be deleted must never be shown
            // as deletable. Non-path findings (command previews) are kept.
            .filter(|f| !f.path.starts_with('/') || self.policy.is_deletable(&f.path).is_ok())
            .collect())
    }

    fn inspect_dir(
        &self,
        id: &str,
        label: &str,
        path: PathBuf,
        disposition: CleanupDisposition,
        destructive: bool,
        rationale: &str,
    ) -> CleanupFinding {
        let bytes = dir_size(&path).unwrap_or(0);
        CleanupFinding {
            id: id.to_string(),
            label: label.to_string(),
            path: path.display().to_string(),
            bytes,
            disposition,
            rationale: rationale.to_string(),
            destructive,
            rollback_kind: Some("metadata-only".to_string()),
        }
    }

    fn inspect_large_downloads(&self, path: PathBuf) -> CleanupFinding {
        let bytes = fs::read_dir(&path)
            .ok()
            .into_iter()
            .flatten()
            .flatten()
            .filter_map(|entry| entry.metadata().ok())
            .filter(|meta| meta.is_file() && meta.len() > 500 * 1024 * 1024)
            .map(|meta| meta.len())
            .sum();

        CleanupFinding {
            id: "large-downloads".to_string(),
            label: "Large forgotten downloads".to_string(),
            path: path.display().to_string(),
            bytes,
            disposition: CleanupDisposition::Review,
            rationale: "Review-only. User files must never be auto-deleted".to_string(),
            destructive: false,
            rollback_kind: None,
        }
    }

    /// See [`plan_token`]; exposed here so callers need no hashing dependency.
    pub fn plan_token_for(targets: &[CleanupFinding]) -> String {
        plan_token(targets)
    }

    /// Delete the contents of a finding's directory.
    ///
    /// Re-validates the finding rather than trusting the caller: a finding that
    /// reached this point through a stale scan, a mutated struct, or a future
    /// call site still cannot delete anything the policy protects.
    pub fn apply(&self, finding: &CleanupFinding) -> Result<()> {
        if !matches!(finding.disposition, CleanupDisposition::SafeAuto) {
            bail!(
                "{} is classified {:?} and needs explicit approval, not automatic cleanup",
                finding.id,
                finding.disposition
            );
        }
        if let Err(refusal) = self.policy.is_deletable(&finding.path) {
            bail!("refusing to purge {}: {refusal}", finding.path);
        }

        let path = PathBuf::from(&finding.path);
        if !path.exists() {
            return Ok(());
        }

        // A symlinked cache directory would redirect the delete elsewhere.
        let meta = fs::symlink_metadata(&path)
            .with_context(|| format!("stat {}", path.display()))?;
        if meta.file_type().is_symlink() {
            bail!("{} is a symlink; refusing to purge", path.display());
        }
        if !meta.is_dir() {
            bail!("{} is not a directory", path.display());
        }

        for entry in fs::read_dir(&path).with_context(|| format!("listing {}", path.display()))? {
            let entry = entry?;
            let child = entry.path();
            let child_meta = fs::symlink_metadata(&child)?;
            if child_meta.is_dir() && !child_meta.file_type().is_symlink() {
                fs::remove_dir_all(&child)
                    .with_context(|| format!("removing {}", child.display()))?;
            } else {
                fs::remove_file(&child).with_context(|| format!("removing {}", child.display()))?;
            }
        }
        Ok(())
    }
}

/// Fingerprint a set of cleanup targets.
///
/// Binds a user's approval to the exact set they were shown: if the scan moves
/// between preview and apply, the token no longer matches and the deletion is
/// refused rather than applied to a set nobody agreed to.
pub fn plan_token(targets: &[CleanupFinding]) -> String {
    let mut hasher = blake3::Hasher::new();
    for finding in targets {
        hasher.update(finding.id.as_bytes());
        hasher.update(b"\0");
        hasher.update(finding.path.as_bytes());
        hasher.update(b"\0");
        hasher.update(&finding.bytes.to_le_bytes());
        hasher.update(b"\n");
    }
    hasher.finalize().to_hex().to_string()
}

fn dir_size(path: &PathBuf) -> Result<u64> {
    let mut total = 0u64;
    if !path.exists() {
        return Ok(0);
    }
    for entry in walkdir::WalkDir::new(path).into_iter().flatten() {
        if let Ok(meta) = entry.metadata() {
            if meta.is_file() {
                total = total.saturating_add(meta.len());
            }
        }
    }
    Ok(total)
}
